### ISSUE TITLE
radar_check only checks first matching PID

### ISSUE THREAD

**Issue by jtc42** [renalreg/radar-patient-check#1]
We have a lot of patients who have multiple records in the UKRDC.

The current logic looks for an NI (NHS/CHI/HSC number) in patientnumbers, and uses the FIRST matching PID to look for program memberships. However, if the first matching record is, for example, a PV feed record, there's no program memberships attached to that PID, so the check returns false.

However, the same NI may still have a RADAR patient record with the membership attached to it.

The code needs to be changed to:

1. Search for all PatientNumber rows with `numbertype` of "NI", and `patientid` matching the request
2. Find all program memberships with a PID matching ANY of those found in step 1
3. Return true if any program memberships are found.

**Comment by andyatterton** [comment]
incorrect it looks for the first radar membership

.filter_by(pid=patient.pid, program_name="RADAR")

**Comment by jtc42** [comment]
Sure, but the point is that at https://github.com/renalreg/radar-patient-check/blob/master/radar_patient_check/main.py#L34 it might be finding a PID that's something like a PV or UKRDC feed patientrecord, which don't hold program memberships. You still need to check for program memberships on ALL the PIDs which match that national ID. You can't just use the first one as it most likely won't be a record that has any program memberships.

**Comment by andyatterton** [comment]
ah okay so a NI can have multiple PID's?

**Comment by jtc42** [comment]
Yeah, so one NHS number will likely link to multiple "patientrecord" rows. Each patientrecord is a separate feed, so if your patient lookup first found a PV record, it would miss the possibly-further-down RADAR record which has a different PID, and thus miss the membership entirely.

It's an easy fix though, see those 3 points in the first comment. It just becomes a filter more liker (not valid code but conveys the point) `.filter_by(pid.in_(matched_record_pids), program_name="RADAR")` where `matched_record_pids` is a list of all the PIDs with a matching NI
